TITLE = "Input text"
GEOMETRY = "400x200"

ENTRY_WIDTH = 30
ENTRY_PADY = 10

FONT = "Arial"

ACCESS_BTN_TEXT = "Так"
ACCESS_BTN_WIDTH = 10
ACCESS_BTN_X = 210
ACCESS_BTN_Y = 150

CANCEL_BTN_TEXT = "Відміна"
CANCEL_BTN_WIDTH = 10
CANCEL_BTN_X = 100
CANCEL_BTN_Y = 150

LABEL_WIDTH = 20 
LABEL_TEXT = "Enter your text:"
LABEL_PADY = 20